stages:
  - build
  - deploy

build-job-php:
  stage: build
  image: sonicgd/php7-nodejs-docker
  artifacts:
    untracked: true
  variables:
    GIT_STRATEGY: fetch
  script:
    - composer global require "fxp/composer-asset-plugin:~1.3"
    - /usr/bin/composer install --no-dev --prefer-dist -o
    - find vendor -type d -name \.git | xargs rm -rf
    - /usr/bin/npm install
    - php init --env=Production --overwrite=All

deploy-job:
  stage: deploy
  image: instrumentisto/rsync-ssh
  only:
    - master
  when: manual
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" > /tmp/key && chmod 0600 /tmp/key && ssh-add /tmp/key && rm /tmp/key
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo $PROD_CONFIG > common/config/main-local.php
    - rsync -Oaz --exclude='.git/' --exclude='.*' . $DEPLOY_USER@$DEPLOY_HOST:$SITE_PATH
    - ssh $DEPLOY_USER@$DEPLOY_HOST "docker exec dockerjupiter_php7_1 bash -c 'cd $SITE_PATH && php yii migrate --interactive=0'"